### ISSUE TITLE
Example of return

### ISSUE THREAD

**Issue by vladi-strilets** [JeandeCampredon/react-native-referrer#10]
Hello, 

Is there some example of the correct return of `RNReferrer.getReferrer()`
I'm getting the next object and can't extract any information from it.
```
{"_40": 0, "_55": null, "_65": 0, "_72": null, "catch": null, "done": null, "finally": null, "then": null}
```
Thanks

**Comment by JeandeCampredon** [comment]
`RNReferrer.getReferrer()` is a promise as described in the readme
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Promise
