### ISSUE TITLE
Support React Native 0.56

### ISSUE THREAD

**Issue by mcrowe** [JeandeCampredon/react-native-referrer#5]
Thanks for this library!

RN 0.56 now uses build tools v26 and this library uses v23. Can you update it so that it will compile properly on 0.56+?

Here is an example of a good way to do this: https://github.com/react-native-community/react-native-svg/blob/master/android/build.gradle

**Comment by JeandeCampredon** [comment]
Omg ! I haven't updated this project for so long ! yes definitely I 'll have some time on it this week-end 👍

**Comment by JeandeCampredon** [comment]
I haven't got the time yet ... keep working on it ... I ll keep you paged

**Comment by mcrowe** [comment]
No problem. Anyone can use this library with RN 0.56+ in the meantime by changing `node_modules/react-native-referrer/android/build.gradle` to:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.facebook.react:react-native:+'
}
```

**Comment by JeandeCampredon** [comment]
ok thanks but I am just a little concerned with retrocompatibility, I ll update it soon
