### ISSUE TITLE
Not Getting Referrer from Play Store URL

### ISSUE THREAD

**Issue by madhavsh27** [JeandeCampredon/react-native-referrer#6]
Hi 

I am using the package in my application to get the user referrer information from Play store but when i am installing the application from Play store url with parameters  utm_source and utm_medium its coming as not set, Can you please let me know what exactly i am doing wrong here.

Thanks
Madhv

**Comment by JeandeCampredon** [comment]
I might need a little more details:
- Have you followed all the installation step ? 
- How does the download link look ?
